CREATE TABLE role (
    idrole INT(10) AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name_role VARCHAR(100) NOT NULL,
    active VARCHAR(1) NOT NULL DEFAULT 'S'
);

CREATE TABLE user (
    iduser INT(10) AUTO_INCREMENT NOT NULL PRIMARY KEY,
    email VARCHAR(50) NULL,
    password VARCHAR(200) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active VARCHAR(1) NOT NULL DEFAULT 'S',
    idrole INT(10),
    FOREIGN KEY (idrole) REFERENCES role(idrole)
);

CREATE TABLE meetings (
    idmeeting INT(10) AUTO_INCREMENT NOT NULL PRIMARY KEY,
    brand VARCHAR(100) NOT NULL,
    model VARCHAR(50) NOT NULL,
    plate VARCHAR(20) NOT NULL,
    date_meeting DATE NOT NULL,
    active VARCHAR(1) NOT NULL DEFAULT 'S'
);